### ISSUE TITLE
知乎文章的封面图是什么意思?

### ISSUE THREAD

**Issue by snowman** [atonasting/marysue-encoder#2]
[闲来无事写了个小玩意+看知乎历史数据下载 - Zhihu](https://zhuanlan.zhihu.com/p/22887287)

![image](https://user-images.githubusercontent.com/16096559/230700109-0af24ed4-e7b8-4899-acde-664d575e673a.png)

密文如下

```璃莹殇·安洁莉娜·樱雪羽晗灵·血丽魑·魅·J·Q·安塔利亚·伤梦薰魅·海瑟薇·蔷薇玫瑰泪·羽灵·邪儿·凡多姆海威恩·夏影·琉璃舞·雅·蕾玥瑷雅·曦梦月·玥蓝·岚樱·紫蝶·丽馨·蕾琦洛·凤·颜鸢·希洛·玖兮·雨烟·叶洛莉兰·凝羽冰·泪伊如冰落·殇心樱语冰凌伊娜·洛丽塔紫心爱·蝶梦如璃紫陌悠千艳·优花梦冰玫瑰灵伤如爱·晶泪墨阳云筱残伤雅·琉璃爱梦莲泪·冰雪殇璃陌梦·爱樱沫渺·落璃琴依语·千梦然丝伤·可薇·茉殇黎·幽幻紫银·泪如韵影倾乐兰慕·冰雪殇璃陌梦·凝羽冰蓝璃·泪伊如琉璃爱梦莲泪·冰雅泪落冰紫蝶梦·殇心```

**Comment by atonasting** [comment]
不是我生成的，是网上找这些字作为素材的时候搜到的……
